# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

config:
  send_anonymous_usage_stats: False

default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DBNAME') }}"
      schema: wh
      threads: 4
